### PR TITLE
Updates from specification feedback

### PR DESCRIPTION
**Pull request by cwgoes**
(tbd)

### CODE REVIEW

**Comment by cwgoes** [comment]
Note for reviewers :writing_hand: :
- You can already review sections 1 & 2, with the exception of section 2.2
- Please don't review anything else yet (but please do review those).

**Comment by cwgoes** [comment]
Tasks (this list is mostly for me):
- [ ] Reorder everything per discussion
- [ ] Update for Isaac's comments in Slack and in https://github.com/anoma/specs/issues/119
- [ ] Update for Yulia's comments in Slack
- [ ] Update terminology re: verifiable computation scheme, proof, argument
- [ ] Update to make all payloads constant-size
- [x] Clarify P2P layering a bit per discussions
- [ ] Start bit about predicate representation (polynomials w/field element type, free parameter of implementation)
- [ ] Fungible & non-fungible token applications
- [ ] Semi-fungible tokens (lose a fraction of value per transfer)
- [ ] Multi-hop routing and settlement
- [ ] Kudos
- [ ] Proof-of-X (bilateral graph relations) sketch

**Comment by cwgoes** [comment]
Note to self:
- Recommend structuring the architecture section based on:
    - Prerequisite primitives
      - As is, but add the physical networking interfaces
    - Common types
      - Identity, resource, entanglement, physical DAG, logical DAGs
    - Logics
      - Transaction execution logic (Taiga)
      - (perhaps also parts of consensus, such as proposer selection)
      - (logics are stateless functions)
    - Engines
      - P2P engine
      - Storage engine (has access to local storage)
      - Compute engine
      - Mempool engine (het. Narwhal)
      - Consensus engine (het. Paxos)
      - Execution engine
      - Identity engine (signing & decryption)
      - Solving engine (partial txs)
      - Interaction engine (communication w/user, both push & pull)

Also:
- Leave out the compiler stack details for now, that can be a separate PR

**Comment by heindel** [comment]
The top level structure makes total sense:
- abstract, like the preface of a book 
- angles of approach, like an introduction to a book 
- scope: _what_ we want to build
- architecture: _how_ we gonna build this
- application: what is it good for

**Comment by degregat** [comment]
Looks great!

Only change I'd suggest is to make `Physical DAG` a subsection of `Logical DAG`.

**Pull request merged**
