### PR TITLE
Changes from @isheff feedback

### PR DESCRIPTION
**Pull request by cwgoes**
(per discussion)

### CODE REVIEW

**Comment by isheff** [comment]
The statement "Anoma provides a ... compiler toolchain" in the first paragraph is still a little awkward, because the paragraph opens with "Anoma is a ... operating system," and operating systems don't traditionally provide a compiler toolchain, or at least the toolchain is not part of the OS per se.

**Comment by isheff** [comment]
Do we need to say "finite & infinite" resources? Couldn't we just say "resources" ?

**Comment by isheff** [comment]
"Intents are" should be "_Intents_ are"

**Comment by isheff** [comment]
"convey the underlying" should be "convey underlying"

**Comment by isheff** [comment]
Attempts to simplify / de-jargonify the sentece "The protocol can be used to instantiate both a system of cybernetic coordination based on arbitrarily interdependent numerical (fungible) measures of value and one dealing purely in relations between actual and possible unique (non-fungible) objects."

- With Anoma, users can coordinate based on both arbitrary fungible measures of value (e.g. currencies) and unique (non-fungible) objects. 
- With Anoma, users engage in cybernetic coordination based both on arbitrary fungible measures of value  (e.g. currencies) and unique (non-fungible) objects. 
  - I'm not sure that "engage in cybernetic coordination" is sufficiently more clear than "coordinate" to justify the increased number of words. 
  
 I'm not sure what the word "interdependent" really means to the reader here, but I don't think it's worth the extra word.

**Comment by isheff** [comment]
Attempts to simplify / de-jargonify: "Insofar as it is used to model the physical world, fungibility can be understood as a lossy dimensionality reduction, and the exact point on the spectrum between the two instantiated in practice may be determined by the practical computational cost tradeoffs."

- I'm not sure we need this sentence at all. We can link the word "fungible" to an article somewhere else about what that means, or just leave it undefined for now. It's an abstract. The notion of a spectrum of fungibility may simply be too much to introduce right here, especially given that we don't use it elsewhere in the abstract. 
- Systems that model the physical world as fungible resources necessarily abstract over some details. Anoma empowers users to customize these abstractions to their needs. In practice, computing cost trade-offs will influence users' abstraction choices.
- Fungible-resource based models of the physical world are necessarily lossy. In practice, computational cost trade-offs may determine the precise models used. 
  - I don't like "models used." it lacks a subject. Used by whom? Then again, I don't want to say "models users use."

**Comment by cwgoes** [comment]
> The statement "Anoma provides a ... compiler toolchain" in the first paragraph is still a little awkward, because the paragraph opens with "Anoma is a ... operating system," and operating systems don't traditionally provide a compiler toolchain, or at least the toolchain is not part of the OS per se.

Changed to "Anoma also comes with a compiler toolchain which allows developers to write Anoma-compatible programs in high-level languages, abstracting the particulars of compilation to the cryptographic primitives required for privacy-preserving operation."

**Comment by cwgoes** [comment]
Changed the jargon-y sentences to "Anoma supports both arbitrary fungible measures of value (e.g. currencies) and unique (non-fungible) objects, so users can choose the representations and level of precision most appropriate to model aspects of the world which they care about.".

**Comment by cwgoes** [comment]
All comments addressed in 138d027, I think.

**Pull request merged**
